package com.rssfeeder.server

import com.rssfeeder.data.model.Article
import com.rssfeeder.data.model.Feed
import java.io.StringWriter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object RssXmlBuilder {

    private val rfc822Format = SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss Z", Locale.US)

    fun buildFeedXml(feed: Feed, articles: List<Article>, baseUrl: String): String {
        val writer = StringWriter()
        val feedUrl = "$baseUrl/feed/${feed.id}/rss.xml"
        val channelLink = if (feed.type == com.rssfeeder.data.model.FeedType.REMOTE) feed.url else feedUrl

        writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        writer.write("<rss version=\"2.0\"\n")
        writer.write("  xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n")
        writer.write("  xmlns:atom=\"http://www.w3.org/2005/Atom\">\n")
        writer.write("  <channel>\n")
        writer.write("    <title>${escapeXml(feed.title)}</title>\n")
        writer.write("    <link>${escapeXml(channelLink)}</link>\n")
        writer.write("    <atom:link href=\"${escapeXml(feedUrl)}\" rel=\"self\" type=\"application/rss+xml\"/>\n")
        writer.write("    <description><![CDATA[Full-text feed generated by RSS-Feeder]]></description>\n")
        writer.write("    <language>en</language>\n")
        writer.write("    <ttl>60</ttl>\n")
        writer.write("    <generator>RSS-Feeder Android</generator>\n")
        writer.write("    <lastBuildDate>${rfc822Format.format(Date())}</lastBuildDate>\n")

        for (article in articles) {
            writer.write("    <item>\n")
            writer.write("      <title>${escapeXml(article.title)}</title>\n")
            writer.write("      <link>${escapeXml(article.link)}</link>\n")
            writer.write("      <guid isPermaLink=\"false\">${escapeXml(article.link)}</guid>\n")
            if (article.author != null) {
                writer.write("      <author>${escapeXml(article.author)}</author>\n")
            }
            if (article.publishedDate > 0) {
                writer.write("      <pubDate>${rfc822Format.format(Date(article.publishedDate))}</pubDate>\n")
            }
            if (article.summary != null) {
                writer.write("      <description>${toCdata(article.summary)}</description>\n")
            }
            val content = article.content ?: article.summary ?: ""
            writer.write("      <content:encoded>${toCdata(content)}</content:encoded>\n")
            writer.write("    </item>\n")
        }

        writer.write("  </channel>\n")
        writer.write("</rss>\n")
        return writer.toString()
    }

    fun buildIndexHtml(feeds: List<Feed>, baseUrl: String): String {
        val writer = StringWriter()
        writer.write("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
        writer.write("<meta charset=\"UTF-8\">\n")
        writer.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
        writer.write("<title>RSS-Feeder</title>\n")
        writer.write("</head>\n<body>\n")
        writer.write("<h1>RSS-Feeder</h1>\n")
        writer.write("<p>Full-text RSS proxy server.</p>\n")
        writer.write("<ul>\n")
        for (feed in feeds) {
            val feedUrl = "$baseUrl/feed/${feed.id}/rss.xml"
            writer.write("  <li><a href=\"$feedUrl\">${escapeXml(feed.title)}</a></li>\n")
        }
        writer.write("</ul>\n</body>\n</html>\n")
        return writer.toString()
    }

    private fun escapeXml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
    }

    private fun toCdata(text: String): String {
        if (!text.contains("]]>")) {
            return "<![CDATA[$text]]>"
        }
        return text.split("]]>").joinToString("") { part ->
            "<![CDATA[$part]]>]]><![CDATA[>"
        }
    }
}
